### ISSUE TITLE
Plotting not working on release_candidate

### ISSUE THREAD

**Issue by aaron-parsons** [ptycho/ptypy#140]
Or at least not for me.
If I set autoplot=True, I now get 
Traceback (most recent call last):
  File "simulation_test_OPR.py", line 77, in <module>
    P = Ptycho(p, level=4)
  File "/home/clb02321/DAWN_nightly/PtypyOPR/ptypy/build/lib/ptypy/core/ptycho.py", line 289, in __init__
    defaults_tree.validate(self.p)
  File "/home/clb02321/DAWN_nightly/PtypyOPR/ptypy/build/lib/ptypy/utils/descriptor.py", line 930, in validate
    d = self.check(pars)
  File "/home/clb02321/DAWN_nightly/PtypyOPR/ptypy/build/lib/ptypy/utils/descriptor.py", line 864, in check
    for res in self._walk(depth=depth, pars=pars):
  File "/home/clb02321/DAWN_nightly/PtypyOPR/ptypy/build/lib/ptypy/utils/descriptor.py", line 841, in _walk
    ignore_wildcards=ignore_wildcards, path=new_path):
  File "/home/clb02321/DAWN_nightly/PtypyOPR/ptypy/build/lib/ptypy/utils/descriptor.py", line 841, in _walk
    ignore_wildcards=ignore_wildcards, path=new_path):
  File "/home/clb02321/DAWN_nightly/PtypyOPR/ptypy/build/lib/ptypy/utils/descriptor.py", line 829, in _walk
    for k, v in pars.items():
AttributeError: 'bool' object has no attribute 'items'

I even tried playing with the default value and I still get nothing.

Am I missing something?

**Comment by alexbjorling** [comment]
Ah this looks like a bug. The Ptycho docstring says autoplot can be bool or Param, but apparently the validator chokes on the bool.

**Comment by aaron-parsons** [comment]
Cool. Pleased it’s not just me! I’ll try to take a look tomorrow. Thanks!

**Comment by pierrethibault** [comment]
There is something wrong on my system so I can't test the fix. But I think that will work. Type validation happens right before (lines 814-821). The mistake was to neglect cases where `pars` was not a `Param`, while `self.children` is not empty because there is the option of being `Param`.

**Comment by pierrethibault** [comment]
Ah Travis chokes the same way my system does. See #141

**Comment by bjoernenders** [comment]
While we are at it, I think we should remove the autoplotter from the default tree. The only thing that Ptycho does is invoking a subprocess. It is more transparent if that happens explicitly in the scripts. That way we could also isolate all the matplotlib from the core.

**Comment by aaron-parsons** [comment]
I've raised a separate issue for the refactor, since I need to think about it a bit more, although I agree that this is the nicest thing to do. For now the plotting works again. We just have an active flag that needs to be set for it to run. This makes the descriptor code nicer than it would be for the multiple types.
