### ISSUE TITLE
mask

### ISSUE THREAD

**Issue by simonesala** [ptycho/ptypy#153]
I'm working on OPRmodel using the AMO_LCLS.py loader, but I suspect this issue is true to the release candidate too.
Whenever providing a mask file to the loader via weight2d from load_weight() it is not used at all by ptypy.
I also tried to change the code and either load it as one mask per frame directly in weights from load() or add 'has_weights = True' at line 694 of 'ptypy/core/data.py' [just before 'assert len(weights) == len(data) ..' if lines are significantly different on the main branch] to force some mask into weights. In both cases I get the following error message whenever running with mpi.

Traceback (most recent call last):
  File "ptypy_DM_29.py", line 101, in <module>
    P = Ptycho(p,level=5)
  File "/home/ss1r15/.local/lib/python2.7/site-packages/ptypy/core/ptycho.py", line 325, in __init__
    self.init_data()
  File "/home/ss1r15/.local/lib/python2.7/site-packages/ptypy/core/ptycho.py", line 462, in init_data
    self.model.new_data()
  File "/home/ss1r15/.local/lib/python2.7/site-packages/ptypy/core/manager.py", line 967, in new_data
    new_data = scan.new_data()
  File "/home/ss1r15/.local/lib/python2.7/site-packages/ptypy/core/manager.py", line 170, in new_data
    dp = self.ptyscan.auto(self.frames_per_call)
  File "/home/ss1r15/.local/lib/python2.7/site-packages/ptypy/core/data.py", line 911, in auto
    self._mpi_save_chunk(self.info.save, msg)
  File "/home/ss1r15/.local/lib/python2.7/site-packages/ptypy/core/data.py", line 1192, in _mpi_save_chunk
    newv = parallel.gather_dict(v)
  File "/home/ss1r15/.local/lib/python2.7/site-packages/ptypy/utils/parallel.py", line 566, in gather_dict
    send(v, dest=target)
  File "/home/ss1r15/.local/lib/python2.7/site-packages/ptypy/utils/parallel.py", line 323, in send
    comm.Send(data, dest=dest, tag=tag)
  File "MPI/Comm.pyx", line 272, in mpi4py.MPI.Comm.Send (src/mpi4py.MPI.c:92648)
  File "MPI/msgbuffer.pxi", line 406, in mpi4py.MPI.message_p2p_send (src/mpi4py.MPI.c:33960)
  File "MPI/msgbuffer.pxi", line 389, in mpi4py.MPI._p_msg_p2p.for_send (src/mpi4py.MPI.c:33828)
  File "MPI/msgbuffer.pxi", line 148, in mpi4py.MPI.message_simple (src/mpi4py.MPI.c:30639)
  File "MPI/msgbuffer.pxi", line 86, in mpi4py.MPI.message_basic (src/mpi4py.MPI.c:29652)
  File "MPI/asbuffer.pxi", line 200, in mpi4py.MPI.getbuffer (src/mpi4py.MPI.c:9565)
  File "MPI/asbuffer.pxi", line 113, in mpi4py.MPI.PyObject_GetBufferEx (src/mpi4py.MPI.c:8355)
ValueError: ndarray is not contiguous

It seems to be working without mpi.
This issue should be addressed on the release candidate too.
More thoughts might be spent on the issue of masks and weights in general: they should remain separate throughout as they have two different roles.

**Comment by pierrethibault** [comment]
We have seen non-contiguous array issues before: #51

**Comment by bjoernenders** [comment]
I found the bug for this. It's in the data preparation. While the data was made contiguous, the mask was ignored for no reason at all.  Already fixed in local branch, will be put upstream today.

**Comment by bjoernenders** [comment]
Closed with commit 83183dde78fa96408af633effe23d4c6066e3ba4
