### ISSUE TITLE
type error in mpi?

### ISSUE THREAD

**Issue by cmkewish** [ptycho/ptypy#202]
On a fresh ubuntu install, with openMPI and ptypy_0.3 cloned from master:

Using a single core: 
`mpiexec -n 1 python minimal_load_and_run.py`

works without error. But, with more than one process
`mpiexec -n 2 python minimal_load_and_run.py`

throws the following KeyError from mpi4py which google only tells me has something to do with mismatching datatypes being passed around.

```
---- Enter PtydScan.initialize() -----------------------------------------------
             Common weight : False
All experimental positions : False
No scanning position have been provided at this stage.
---- Leaving PtyScan.initialize() ----------------------------------------------
Time 0.00
Importing data from scan MF.
Traceback (most recent call last):
  File "minimal_load_and_run.py", line 33, in <module>
    P = Ptycho(p,level=5)
  File "/home/user/.local/lib/python2.7/site-packages/ptypy/core/ptycho.py", line 347, in __init__
    self.init_data()
  File "/home/user/.local/lib/python2.7/site-packages/ptypy/core/ptycho.py", line 484, in init_data
    self.model.new_data()
  File "/home/user/.local/lib/python2.7/site-packages/ptypy/core/manager.py", line 1314, in new_data
    new_data = scan.new_data()
  File "/home/user/.local/lib/python2.7/site-packages/ptypy/core/manager.py", line 182, in new_data
    dp = self.ptyscan.auto(self.frames_per_call)
  File "/home/user/.local/lib/python2.7/site-packages/ptypy/core/data.py", line 897, in auto
    msg = self.get_data_chunk(frames)
  File "/home/user/.local/lib/python2.7/site-packages/ptypy/core/data.py", line 665, in get_data_chunk
    indices)
  File "/home/user/.local/lib/python2.7/site-packages/ptypy/core/data.py", line 966, in _mpi_pipeline_with_dictionaries
    pos = parallel.gather_dict(pos)
  File "/home/user/.local/lib/python2.7/site-packages/ptypy/utils/parallel.py", line 580, in gather_dict
    send(v, dest=target)
  File "/home/user/.local/lib/python2.7/site-packages/ptypy/utils/parallel.py", line 331, in send
    comm.Send(data, dest=dest, tag=tag)
  File "mpi4py/MPI/Comm.pyx", line 271, in mpi4py.MPI.Comm.Send
  File "mpi4py/MPI/msgbuffer.pxi", line 396, in mpi4py.MPI.message_p2p_send
  File "mpi4py/MPI/msgbuffer.pxi", line 379, in mpi4py.MPI._p_msg_p2p.for_send
  File "mpi4py/MPI/msgbuffer.pxi", line 154, in mpi4py.MPI.message_simple
  File "mpi4py/MPI/msgbuffer.pxi", line 100, in mpi4py.MPI.message_basic
KeyError: '<d'
[asciproto05:11402] 1 more process has sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
[asciproto05:11402] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```
Does that mean anything to anyone else?

Thanks

**Comment by bjoernenders** [comment]
Hi Cameron,
thanks for opening this issue. Does the same problem occur for minimal_prep_and_run.py? Otherwise it could be that the h5py library does not support mpi. So it could be that the h5read comes back on the second rank with None where there should be an array, causing a type mismatch. Juliane mentioned this error before. Maybe try another compute node or the laptop to narrow down the error.
Best, Bjoern

**Comment by pierrethibault** [comment]
Hi Cameron, I got the same error on my system. For some reason the positions loaded from the prepared files have the wrong byte order (or byte order flag?). I have added a try/except in parallel for these cases. Can you please try if branch `issue-202` solves it for you too?

**Comment by cmkewish** [comment]
Hi Pierre, thanks for looking into this. I confirm that branch `issue-202` does indeed solve this issue for me. I was able to run `minimal_load_and_run.py` on a single Ubuntu machine with up to 32 cores, with the expected performance increase per-core, more or less.

**Comment by bjoernenders** [comment]
@pierrethibault @cmkewish Is this an h5py or an mpi4py issue? I'm a bit confused.

**Comment by pierrethibault** [comment]
I don't know! Maybe just incompatibility. Looks like h5py does not enforce the "native" label onto some datasets (here '<' instead of '='), and that mpi4py is not happy with this. Currently the "fix" I have implemented is at the mpi end because we have much more control there then at the h5py part, which is implemented by users.

**Comment by pierrethibault** [comment]
There's something strange. I tested the behaviour running the following with `mpiexec -n 2`:
```
import numpy as np
from mpi4py import MPI

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

for bytestr in ['=', '<', '>']:
    x = np.array([0., 1., 2.]).astype(bytestr + 'd')

    # Test reduce
    x1 = comm.allreduce(x)

    if rank==0: print('Reduce "%sd" success' % bytestr)

    # Test one-way send
    if rank==0: 
        comm.Send(x, dest=1, tag=0)
    if rank==1: 
        comm.Recv(x, source=0, tag=0)

    if rank==0: print('Send/Recv "%sd" success' % bytestr)
```
But I get an error only for the big-endian (">") case, whereas the error in ptypy is for "<", which should be the same as native. Unless someone feels like digging into this, I'd just merge my fix.
