### ISSUE TITLE
KeyError: 'autoplot' in ptypy.plotclient related to issue #127

### ISSUE THREAD

**Issue by jcesardasilva** [ptycho/ptypy#221]
Cannot use ptypy.plotclient because it complains because of KeyError. The problem seems to appear in defaults_tree['io.autoplot'].
```
$ ptypy.plotclient
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mntdirect/_data_id16a_inhouse1/sware/pyvenvid16a/pyid16a/bin/ptypy.plotclient", line 9, in <module>
    plot_desc = defaults_tree['io.autoplot']
  File "/mntdirect/_data_id16a_inhouse1/sware/pyvenvid16a/pyid16a/lib/python2.7/site-packages/ptypy/utils/descriptor.py", line 216, in __getitem__
    return self.children[root][name]
  File "/mntdirect/_data_id16a_inhouse1/sware/pyvenvid16a/pyid16a/lib/python2.7/site-packages/ptypy/utils/descriptor.py", line 218, in __getitem__
    return self.children[name]
KeyError: 'autoplot'
```

**Comment by pierrethibault** [comment]
Sorry for the delay Julio. I think it should be solved now.
