### ISSUE TITLE
Some scripts in templates seem broken

### ISSUE THREAD

**Issue by jcesardasilva** [ptycho/ptypy#264]
I have notice that some of the scripts in templates folder are not running properly. In particular, the following ones:

- `position_evalution.py` which gives the following error:
```
Traceback (most recent call last):
File "position_evaluation.py", line 42, in <module>
    print(pos_trajec.shape)
NameError: name 'pos_trajec' is not defined
```
- `python3 ptypy_id22ni_AuStar_focussed_17keV.py` and `ptypy_i13_AuStar_nearfield_9p7keV.py` with similar error:
```
Traceback (most recent call last):
  File "ptypy_id22ni_AuStar_focussed_17keV.py", line 110, in <module>
    P = Ptycho(p,level=5)
  File "/usr/local/lib/python3.8/site-packages/ptypy/core/ptycho.py", line 344, in __init__
    self.init_structures()
  File "/usr/local/lib/python3.8/site-packages/ptypy/core/ptycho.py", line 473, in init_structures
    self.model = ModelManager(self, self.p.scans)
  File "/usr/local/lib/python3.8/site-packages/ptypy/core/manager.py", line 1586, in __init__
    self.scans[label] = cls(ptycho=self.ptycho, pars=scan_pars, label=label)
  File "/usr/local/lib/python3.8/site-packages/ptypy/core/manager.py", line 127, in __init__
    self.ptyscan = self.makePtyScan(self.p.data)
  File "/usr/local/lib/python3.8/site-packages/ptypy/core/manager.py", line 176, in makePtyScan
    ps_instance = ps_class(pars)
  File "/usr/local/lib/python3.8/site-packages/ptypy/simulations/simscan.py", line 154, in __init__
    P=Ptycho(pp,level=2)
  File "/usr/local/lib/python3.8/site-packages/ptypy/core/ptycho.py", line 347, in __init__
    self.init_data()
  File "/usr/local/lib/python3.8/site-packages/ptypy/core/ptycho.py", line 484, in init_data
    self.model.new_data()
  File "/usr/local/lib/python3.8/site-packages/ptypy/core/manager.py", line 1618, in new_data
    new_data = scan.new_data()
  File "/usr/local/lib/python3.8/site-packages/ptypy/core/manager.py", line 358, in new_data
    self._initialize_object(new_object_ids)
  File "/usr/local/lib/python3.8/site-packages/ptypy/core/manager.py", line 1168, in _initialize_object
    sample.init_storage(s, sample_pars)
  File "/usr/local/lib/python3.8/site-packages/ptypy/core/sample.py", line 283, in init_storage
    model = simulate(model, p.process, energy, p.fill, prefix)
  File "/usr/local/lib/python3.8/site-packages/ptypy/core/sample.py", line 379, in simulate
    result = np.array(u.cxro_iref(p.formula,
  File "/usr/local/lib/python3.8/site-packages/ptypy/utils/scripts.py", line 809, in cxro_iref
    dt = np.array([[float(x) for x in dd.split()] for dd in d[2:] if dd])
  File "/usr/local/lib/python3.8/site-packages/ptypy/utils/scripts.py", line 809, in <listcomp>
    dt = np.array([[float(x) for x in dd.split()] for dd in d[2:] if dd])
  File "/usr/local/lib/python3.8/site-packages/ptypy/utils/scripts.py", line 809, in <listcomp>
    dt = np.array([[float(x) for x in dd.split()] for dd in d[2:] if dd])
ValueError: could not convert string to float: '<meta'
```

**Comment by jcesardasilva** [comment]
Solved this problem by changing `http` to `https` at line 748, corresponding to `_cxro_server = 'https://henke.lbl.gov' ` from file  ptypy/utils/scripts.py. 

I will prepare a pull request soon.
