### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by Amirafsharm** [ptycho/ptypy#374]
Hi,
I have installed ptypy using 
`python setup.py install --user`
on windows 10, in an environment with python 2.7.13. 
I try to run examples in ptypy\templates folder, but I receive the `ImportError: No module named request` error message.
Here is the full message:

`(ptypyenv) D:\ptycho>python ptypy-master\templates\minimal_prep_and_run.py 
Traceback (most recent call last):
  File "ptypy-master\templates\minimal_prep_and_run.py", line 7, in <module>
    from ptypy.core import Ptycho
  File "C:\Users\Amirafshar\AppData\Roaming\Python\Python27\site-packages\ptypy\__init__.py", line 45, in <module>
    from .utils import parallel
  File "C:\Users\Amirafshar\AppData\Roaming\Python\Python27\site-packages\ptypy\utils\__init__.py", line 13, in <module>
    from .scripts import *
  File "C:\Users\Amirafshar\AppData\Roaming\Python\Python27\site-packages\ptypy\utils\scripts.py", line 12, in <module>
    import urllib.request, urllib.error, urllib.parse
ImportError: No module named request`

Would you help me with that?

**Comment by daurer** [comment]
@Amirafsharm contrary to what our documentation says (@bjoernenders we should really update this) PtyPy has been fully upgraded to Python 3 and we no longer support Python 2. 

Maybe you could try again in an environment with Python >= 3.7 ?

**Comment by Amirafsharm** [comment]
@daurer Thanks for the quick response. I will try with Python 3.8 and keep you posted.

**Comment by Amirafsharm** [comment]
I could install it on windows 10 with 
`python --version = 3.7.11;
pip --version = 21.2.4;
conda --version  = 4.10.3`.
I attached the environment details.
[ptypy_environment.txt](https://github.com/ptycho/ptypy/files/7487841/ptypy_environment.txt)
