### ISSUE TITLE
Working on windows?

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#91]
One of my users is considering switching to ptypy. The problem is that he wants to do it on windows.

He's reporting 3 symptoms (see output)
* Everything that ptypy prints is printed 4 times (is it doing MPI by itself?). But stuff from the nanomax PtyScan is printed only once.
* Automatic COM guessing fails miserably and gives negative values
* After that, it crashes in a way suggesting that the imports don't work, saying that `logger` and `parallel` are `None`.

This behavior makes me feel that there's something windows-incompatible at least with the way imports are done. Does anyone know if the current code can run on windows at all?

~~~
loading data: scan_0192_pil100k_0016.hdf5
> loading normalization data: scan_0192_pil100k_0016.hdf5
> normalizing line by:  [
> 1.05667706  1.06190191  1.06141107  1.0556026   1.03927968  1.0199902
> 6
>  
> 0.99759464  0.9760873   0.95855387  0.95383338  0.96124094  0.9831006
> 6
>  
> 1.01826523  1.05484035  1.08091398  1.0938926   1.09300157  1.0904335
> 1
>   1.08815937  1.08427569  1.07589705]
> loaded 17 lines of Pilatus data
> ROI center is [ 98 238], automatic guess is [-27.08123249
> -12.78431373].
> ROI center is [ 98 238], automatic guess is [-27.08123249
> -12.78431373].
> ROI center is [ 98 238], automatic guess is [-27.08123249
> -12.78431373].
> ROI center is [ 98 238], automatic guess is [-27.08123249
> -12.78431373].
> Enter preprocessing (crop/pad True, rebin False, flip/rotate False)
> ... 
> 
> Enter preprocessing (crop/pad True, rebin False, flip/rotate False)
> ... 
> 
> Enter preprocessing (crop/pad True, rebin False, flip/rotate False)
> ... 
> 
> Enter preprocessing (crop/pad True, rebin False, flip/rotate False)
> ... 
> 
> Feeding data chunk
> Feeding data chunk
> Feeding data chunk
> Feeding data chunk
> Importing data from NM as scan NM.
> Importing data from NM as scan NM.
> Importing data from NM as scan NM.
> Importing data from NM as scan NM.
> End of scan reached
> End of scan reached
> End of scan reached
> End of scan reached
> End of scan reached
> End of scan reached
> End of scan reached
> End of scan reached
> C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-
> packages\ptypy\core\geometry.py:434: FutureWarning: elementwise
> comparison failed; returning scalar instead, but in the future will
> perform elementwise comparison
>   if str(p.center) == p.center:
> C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-
> packages\ptypy\utils\array_utils.py:208: FutureWarning: elementwise
> comparison failed; returning scalar instead, but in the future will
> perform elementwise comparison
>   if center=='fftshift':
> C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-
> packages\ptypy\utils\array_utils.py:210: FutureWarning: elementwise
> comparison failed; returning scalar instead, but in the future will
> perform elementwise comparison
>   elif center=='geometric':
> C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-
> packages\ptypy\utils\array_utils.py:212: FutureWarning: elementwise
> comparison failed; returning scalar instead, but in the future will
> perform elementwise comparison
>   elif center=='fft':
> 
> --- Scan NM photon report ---
> Total photons   : 1.22e+10 
> Average photons : 3.42e+07
> Maximum photons : 3.43e+07
> -----------------------------
> 
> --- Scan NM photon report ---
> Total photons   : 1.22e+10 
> Average photons : 3.42e+07
> Maximum photons : 3.43e+07
> -----------------------------
> 
> --- Scan NM photon report ---
> Total photons   : 1.22e+10 
> Average photons : 3.42e+07
> Maximum photons : 3.43e+07
> -----------------------------
> 
> --- Scan NM photon report ---
> Total photons   : 1.22e+10 
> Average photons : 3.42e+07
> Maximum photons : 3.43e+07
> -----------------------------
> 
> ---- Creating PODS --------------------------------------------------
> -----------
> 
> ---- Creating PODS --------------------------------------------------
> -----------
> 
> ---- Creating PODS --------------------------------------------------
> -----------
> 
> ---- Creating PODS --------------------------------------------------
> -----------
> Found these probes : 
> Found these probes : 
> Found these probes : 
> Found these probes : 
> Found these objects: 
> Found these objects: 
> Found these objects: 
> Found these objects: 
> Process 0 created 357 new PODs, 1 new probes and 1 new objects.
> Process 0 created 357 new PODs, 1 new probes and 1 new objects.
> Traceback (most recent call last):
>   File "C:\Users\dsf-user\Anaconda2\lib\logging\__init__.py", line
> 861, in emit
>     msg = self.format(record)
>   File "C:\Users\dsf-user\Anaconda2\lib\logging\__init__.py", line
> 734, in format
>     return fmt.format(record)
>   File "C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-
> packages\ptypy\utils\verbose.py", line 96, in format
>     return logging.Formatter.format(self, record)
> AttributeError: 'NoneType' object has no attribute 'Formatter'
> Logged from file manager.py, line 603
> Traceback (most recent call last):
>   File "C:\Users\dsf-user\Anaconda2\lib\logging\__init__.py", line
> 861, in emit
>     msg = self.format(record)
>   File "C:\Users\dsf-user\Anaconda2\lib\logging\__init__.py", line
> 734, in format
>     return fmt.format(record)
>   File "C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-
> packages\ptypy\utils\verbose.py", line 96, in format
>     return logging.Formatter.format(self, record)
> AttributeError: 'NoneType' object has no attribute 'Formatter'
> Logged from file manager.py, line 603
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\dsf-user\Anaconda2\lib\site-
> packages\spyderlib\widgets\externalshell\sitecustomize.py", line 523,
> in runfile
>     execfile(filename, namespace)
>   File "C:\Users\dsf-
> user\Documents\GitHub\ptypy\Jesper\reconstruction_pilatus.py", line
> 103, in <module>
>     P = Ptycho(p,level=5)
>   File "C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-
> packages\ptypy\core\ptycho.py", line 193, in __init__
>     self.init_data()
>   File "C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-
> packages\ptypy\core\ptycho.py", line 338, in init_data
>     self.modelm.new_data()
>   File "C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-
> packages\ptypy\core\manager.py", line 610, in new_data
>     self._initialize_probe(new_probe_ids)
>   File "C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-
> packages\ptypy\core\manager.py", line 618, in _initialize_probe
>     logger.info('\n' + headerline('Probe initialization', 'l'))
>   File "C:\Users\dsf-user\Anaconda2\lib\logging\__init__.py", line
> 1167, in info
>     self._log(INFO, msg, args, **kwargs)
>   File "C:\Users\dsf-user\Anaconda2\lib\logging\__init__.py", line
> 1286, in _log
>     self.handle(record)
>   File "C:\Users\dsf-user\Anaconda2\lib\logging\__init__.py", line
> 1295, in handle
>     if (not self.disabled) and self.filter(record):
>   File "C:\Users\dsf-user\Anaconda2\lib\logging\__init__.py", line
> 617, in filter
>     if not f.filter(record):
>   File "C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-
> packages\ptypy\utils\verbose.py", line 78, in filter
>     return self.allprocesses or parallel.master
> AttributeError: 'NoneType' object has no attribute 'master'
~~~

**Comment by jesperwallentin** [comment]
I'm the windows user...

When I use the autoplot, I get the following message (with autoplot diabled, it doesn't appear):

```python

Iteration #2 of DM :: Time 3.66
Errors :: Fourier 5.79e+02, Photons 1.11e+04, Exit 2.32e+02
C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-packages\ptypy\core\geometry.py:434: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if str(p.center) == p.center:
C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-packages\ptypy\utils\array_utils.py:208: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if center=='fftshift':
C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-packages\ptypy\utils\array_utils.py:210: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif center=='geometric':
C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-packages\ptypy\utils\array_utils.py:212: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif center=='fft':
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\dsf-user\Anaconda2\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Users\dsf-user\Anaconda2\lib\multiprocessing\forking.py", line 509, in prepare
    '__parents_main__', file, path_name, etc
  File "C:\Users\dsf-user\Documents\GitHub\ptypy\Jesper\reconstruction_pilatus_JW1.py", line 107, in <module>
    P = Ptycho(p,level=5)
  File "C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-packages\ptypy\core\ptycho.py", line 196, in __init__
    self.init_communication()
  File "C:\Users\dsf-user\AppData\Roaming\Python\Python27\site-packages\ptypy\core\ptycho.py", line 291, in init_communication
    self.plotter.start()
  File "C:\Users\dsf-user\Anaconda2\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Users\dsf-user\Anaconda2\lib\multiprocessing\forking.py", line 258, in __init__
    cmd = get_command_line() + [rhandle]
  File "C:\Users\dsf-user\Anaconda2\lib\multiprocessing\forking.py", line 358, in get_command_line
    is not going to be frozen to produce a Windows executable.''')
RuntimeError: 
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
```

**Comment by alexbjorling** [comment]
Another bug is that os.rename doesn't work on windows if the target file exists. Did a workaround on the nanomax branch [commit 80dfe70](https://github.com/ptycho/ptypy/commit/80dfe70340c3493109fad8c18081abebf0141328). I think the same fix could go into master.

**Comment by alexbjorling** [comment]
OK so some of the symptoms above were caused by running many times in the same interpreter. 

But still, there's an `os.rename` bug (previous comment), the COM determination doesn't work, and spawning the plot thread crashes as mentioned.

**Comment by bjoernenders** [comment]
The plot Thread will be abandoned in future versions. But you can also manual disable autoplotting and run the plot thread in a separate process. Try `io.autoplot` = `False` or `None`.

Have you seen PyInstaller for cross platform deployment? Maybe that is an option:
https://pyinstaller.readthedocs.io/en/stable/index.html

**Comment by alexbjorling** [comment]
Thanks Björn, I didn't know if PyInstaller.

Running the plotter separately is a good idea, I think there is even an issue with running ptypy.plot on windows, it doesn't like the extension or something (or how was it @jesperwallentin?). Maybe consider renaming it for compatibility.

I will look into the COM determination issue if I find the time.

**Comment by jesperwallentin** [comment]
I haven't tried PyInstaller, but I think Anaconda worked fine. 
ptypy.plot created problems because Windows 10 interprets the .plot as a file extension. Perhaps there is a good way of circumventing that, but I renamed it to ptypy_plot.py and run it from Spyder.

**Comment by alexbjorling** [comment]
I am unable to reproduce the COM error on this windows machine. @jesperwallentin check that the data is loaded correctly because the code that finds the COM looks very simple and should work.

_edit: I used the wrong data, it reproduces just fine, see debug below._

**Comment by alexbjorling** [comment]
On my windows machine, ptypy.plot doesn't work at all (even after fixing the bug introduced by PR #76) - it just hangs. But the script I normally use for plotting reconstructions does work, so @jesperwallentin you could try that and strip or modify it as you like.

https://github.com/alexbjorling/nanomax-analysis-utils
https://github.com/alexbjorling/nanomax-analysis-utils/blob/master/apps/plotPtypyResults.py

**Comment by alexbjorling** [comment]
Ok the COM error is because of an overflow in the weighted sum of `utils.mass_center`.

```python
return np.sum(A * np.indices(A.shape), axis=axes) / np.sum(A)
```

Debugging on windows (wrong):
```python
(Pdb) A.dtype
dtype('int32')
(Pdb) np.indices(A.shape).dtype
dtype('int32')
(Pdb) np.sum(A * np.indices(A.shape), axis=axes).dtype
dtype('int32')
(Pdb) np.sum(A * np.indices(A.shape), axis=axes)
array([-920539807, -411794863])
```

Debugging on linux (correct):
```
ipdb> A.dtype
dtype('int32')
ipdb> np.indices(A.shape).dtype
dtype('int64')
ipdb> np.sum(A * np.indices(A.shape), axis=axes).dtype
dtype('int64')
ipdb> np.sum(A * np.indices(A.shape), axis=axes)
array([3374427489, 8178139729])
```

So apparently on windows, np.indices gives an `int32` by default, but on my linux box it gives an `int64`. The result is that on windows the sum of (high photon counts * a potentially high pixel index) overflows the `int32`.

The solution is either to supply `dtype=np.int64` to `np.sum`, or to use something like `scipy.ndimage.center_of_mass`. Marking this as a bug. For now @jesperwallentin, you'll have to specify `p.scans.xxx.data.center` manually.

**Comment by jesperwallentin** [comment]
Thanks Alex. 
Seems to be a general feature of numpy on windows 10: [https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine](url)

**Comment by alexbjorling** [comment]
OK closing this issue. 

Plotting on windows doesn't seem to work but that can be done outside of ptypy. Let's make sure that future plotters are portable.
