### ISSUE TITLE
Is the simulations module working?

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#99]
I'm making slides, and thought I would replace some of my own simulations with ptypy ones.

However, running `simscan.py` as `__main__` throws an error. I wonder if the simulations code is working, or if it has broken because of changes elsewhere? This relates to issue #67 about broken, unused and deprecated code.

```
alex@w-alebjo-pc-0:~$ python code/ptypy/ptypy/simulations/simscan.py
Verbosity set to 3
Generating simulating Ptycho instance for scan `None`.
Verbosity set to 1
Traceback (most recent call last):
  File "code/ptypy/ptypy/simulations/simscan.py", line 237, in <module>
    MS = SimScan(None,s)
  File "code/ptypy/ptypy/simulations/simscan.py", line 117, in __init__
    P=Ptycho(pp,level=2)
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/core/ptycho.py", line 193, in __init__
    self.init_data()
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/core/ptycho.py", line 338, in init_data
    self.modelm.new_data()
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/core/manager.py", line 336, in new_data
    dp = self.ptycho.datasource.feed_data()
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/core/data.py", line 1526, in feed_data
    msg = cur_scan.auto(self.frames_per_call, self.feed_format)
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/core/data.py", line 820, in auto
    msg = self.get_data_chunk(frames)
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/core/data.py", line 561, in get_data_chunk
    msg = self._mpi_check(chunksize, start)
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/core/data.py", line 500, in _mpi_check
    self.frames_accessible, eos = self.check(chunksize, start=s)
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/core/data.py", line 957, in check
    frames_accessible = min((frames, self.num_frames - start))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by alexbjorling** [comment]
If the simulations module isn't working, then couldn't we just replace it by a simple template such as this?

```python
import ptypy
import numpy as np
from scipy.misc import face, imresize

# define probe and object
probe = np.zeros((128,128)) 
probe[32:-32, 32:-32] = 1
obj = imresize(face(gray=True), .3) / 255.

# set up geometry
geo = ptypy.core.geometry.Geo(shape=probe.shape)

# set up scan
density = .2
probe_frame = geo.resolution[0] * geo.shape[0]
positions = ptypy.core.xy.spiral_scan(dr=density*probe_frame, r=np.min(obj.shape[0])/2*geo.resolution[0])

# object storage
Cobj = ptypy.core.Container(data_type='complex')
Sobj = Cobj.new_storage(ID='Sobj', psize=geo.resolution, shape=obj.shape)
Sobj.data[:] = obj
for pos in positions:
    ptypy.core.View(Cobj, storageID='Sobj', psize=geo.resolution, coord=pos, shape=geo.shape)
Cobj.reformat()

# calculate diffraction patterns
diff = []
for v in Sobj.views:
    diff.append(np.abs(geo.propagator.fw(v.data * probe))**2)
diff = np.array(diff)

# then generate a ptyd file or whatever
```

**Comment by bjoernenders** [comment]
Hi Alex,

the 'official' simulations are those in the templates/  directory. These actually use the `SimScan` class. At least the cSAXS sim is still working. The one you were using was for testing the module and it became outdated once we actually start using the templates. I provide a fix for the direct module call. 

Best Bjoern

**Comment by bjoernenders** [comment]
See commit 4674714 and 805af79. Hope that resolves it for now. Have a look at the templates if there is something you want to start from. But pleasse add your script to the templates as an example how to bypass Ptycho.

Best Bjoern

**Comment by alexbjorling** [comment]
Ok, thanks for the fix and cleanup!
